eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    enable-ignore-connection-close-header: true
  metrics:
    polling-interval-ms: 200
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream