server:
  port: 8771
spring:
  rabbitmq:
    host: 192.168.126.138
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
