server:
  port: 8770
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/linjinbao66/springcloudconfig/
          search-paths: config
          username:
          password:
      label: master

